### ISSUE TITLE
Multiple requests to Custom Search API for a single screenshot

### ISSUE THREAD

**Issue by jonah-walker** [radixdev/trivia-assistant#3]
Instead of only making one request to the Custom Search API, taking one screenshot will often make 2-4 requests, sending multiple toasts to the user. This can quickly use up the daily quota of 100 requests that Google provides for free.

**Comment by radixdev** [comment]
This is 100% intended. 

See [the searcher](https://github.com/radixdev/trivia-assistant/blob/master/app/src/main/java/com/radix/triviaassistant/network/QuestionSearcher.java#L33) and [the StrategyEngine](https://github.com/radixdev/trivia-assistant/blob/master/app/src/main/java/com/radix/triviaassistant/strategy/StrategyEngine.java#L44).
